version: '3'
services: 
  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    working_dir: /code
    ports: 
      - 3333:3333

  mongo:
    image: 'mongo:4.0.11'
    container_name: mongo
    volumes:
      - mongo:/data/db
    ports: 
      - 27017:27017
      - 28017:28017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo: